### ISSUE TITLE
为什么我用chrome打开渲染出的目录与插图不同？

### ISSUE THREAD

**Issue by AHU-HUI** [alanwei43/epubit-ebook-download#2]
chrome中目录背景色为蓝色，且覆盖在正文页面上方，比例为适应宽度
![image](https://user-images.githubusercontent.com/26405409/82147875-573d6300-9883-11ea-8f54-ace4b9ce5661.png)

**Comment by alanwei43** [comment]
> 景色为蓝色，

样式你可以随便调整的，修改文件 `reader/public/styles.css` , 然后进入 `reader`目录 执行 `npm run build` 即可. README.md 的截图样式比较老了，后来有更新了。

**Comment by alanwei43** [comment]
最新版阅读界面是这样的
<img width="597" alt="Screen Shot 2020-05-22 at 21 15 01" src="https://user-images.githubusercontent.com/2927578/82671413-64869300-9c71-11ea-8b1b-d40e86e8fe49.png">

**Comment by AHU-HUI** [comment]
建议限制正文页面的宽度，图片自动居中，目录不要悬浮在正文上方（不懂前端，一点小小的建议）

**Comment by alanwei43** [comment]
> 建议限制正文页面的宽度，图片自动居中，目录不要悬浮在正文上方（不懂前端，一点小小的建议）

已经增加了设置项, 可以自定义宽度、对齐、行高等, 获取最新代码刷新页面就可以看到效果了:
<img width="592" alt="Screen Shot 2020-05-23 at 15 08 43" src="https://user-images.githubusercontent.com/2927578/82724290-7d418800-9d07-11ea-9903-7fc818f05f62.png">

另外你说的目录不要悬浮这个问题, 我看大部分阅读网站的目录都是悬浮的吧, 不然目录就会挤占可视空间.

**Comment by AHU-HUI** [comment]
可以自定义宽度后，目录不会悬浮在正文上方可以接受。试用了一下，非常棒！感谢你的付出！
